### ISSUE TITLE
Krakend configuration for multiple apps with same URL pattern

### ISSUE THREAD

**Issue by fabubacker** [krakend/krakend-ce#821]
**Environment info:**

* KrakenD version: Version: 2.4.6
* System info: NA
* Hardware specs: NA
* Backend technology: NA
* Additional environment information: Testing it in local at this moment using docker and yet to be deployed to our environment. Provided docker command below which I used for my testing.

**Describe what are you trying to do**:
I have two applications (App1 and App2) running on a kubernetes cluster. They have similar URL pattern but differentitated only by the domain name. Provided some example url below for reference. All are GET request.
**App 1 URL List:** 
- https://app1.example.com/
- https://app1.example.com/foo
- https://app1.example.com/foo/bar

**App 2 URL List:**
- https://app2.example.com/
- https://app2.example.com/foo
- https://app2.example.com/foo/bar

We are planning to implement Krakend as api gateway infront of these apps. I have tried configuring krakend.json but it looks like it is not possible because we cannot have multiple endpoints with same value. I have also tried adding [Conditional requests and responses with CEL](https://www.krakend.io/docs/endpoints/common-expression-language-cel/) by checking the Host request header in `check_expr` something like below and it is also not working as I am getting the error `[request aborted by evaluator #0](panic: handlers are already registered for path '/')` when starting the Krakend.

I am looking for some suggestion on how to configure Krakend for multiple apps having similar URL pattern but differentiated by domain names. I do not want to have multiple Krakend deployment as it will be difficult to manage when more apps started to onboard. I have tried some ingress level changes to rewrite the target of each apps by appending a context root something line https://app1.example.com/app1 and https://app2.example.com/app2 before hitting Krakend but it is redirecting the url at browser level which I do not want. The important thing to consider here is, I do not want the URL to be changed for end customer. Hope I explained things clear. Let me know for any more info.
 
**Your configuration file**:

This below example is only for `/`.
```json
{
  "version": 3,
  "timeout": "10s",
  "port": 80,
  "endpoints": [
    {
      "endpoint": "/",
      "output_encoding": "no-op",
      "input_headers": [
        "Host"
      ],
      "extra_config": {
        "validation/cel": [
          {
              "check_expr": "'app1.example.com' in req_headers['Host']"
          }
      ]
      },
      "backend": [
        {
          "url_pattern": "/",
          "host": [
            "app1.app1namespace.svc.cluster.local:8080"
          ]
        }
      ]
    },
    {
      "endpoint": "/",
      "output_encoding": "no-op",
      "input_headers": [
        "Host"
      ],
      "extra_config": {
        "validation/cel": [
          {
              "check_expr": "'app2.example.com' in req_headers['Host']"
          }
      ]
      },
      "backend": [
        {
          "url_pattern": "/",
          "host": [
            "app2.app2namespace.svc.cluster.local:8080"
          ]
        }
      ]
    }
  ]
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
$ krakend check -dtc krakend.json --lint
Parsing configuration file: krakend.json
Global settings
        Name:
        Port: 80
2 API endpoint(s):
        - GET /
        Timeout: 10s
        1 endpoint component configuration(s):
        - validation/cel
        Connecting to 1 backend(s):
                [+] GET /
                Timeout: 10s
                Hosts: [http://app1.app1namespace.svc.cluster.local:8080]

        - GET /
        Timeout: 10s
        1 endpoint component configuration(s):
        - validation/cel
        Connecting to 1 backend(s):
                [+] GET /
                Timeout: 10s
                Hosts: [http://app2.app2namespace.svc.cluster.local:8080]

0 async agent(s):
ERROR testing the configuration file:   handlers are already registered for path '/'
```

**Commands used:**
How did you start the software?
```
docker run -p 80:80 -v "${PWD}:/etc/krakend/" -e "FC_ENABLE=1" devopsfaith/krakend run -d -c /etc/krakend/krakend.json
```

**Logs:**
```
2023/11/27 22:45:55 KRAKEND INFO: Starting KrakenD v2.4.6
Parsing configuration file: /etc/krakend/krakend.json
2023/11/27 22:45:55 KRAKEND DEBUG: [SERVICE: Gin] Debug enabled
2023/11/27 22:45:55 KRAKEND INFO: Starting the KrakenD instance
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /] Building the proxy pipe
2023/11/27 22:45:55 KRAKEND DEBUG: [BACKEND: /] Building the backend pipe
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][CEL] Loading configuration
2023/11/27 22:45:55 KRAKEND DEBUG: [CEL] Parsing expression: 'app1.example.com' in req_headers['Host']
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][CEL] 1 preEvaluator(s) loaded
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][CEL] 0 postEvaluator(s) loaded
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /] Building the http handler
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][JWTSigner] Signer disabled
2023/11/27 22:45:55 KRAKEND INFO: [ENDPOINT: /][JWTValidator] Validator disabled for this endpoint
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /] Building the proxy pipe
2023/11/27 22:45:55 KRAKEND DEBUG: [BACKEND: /] Building the backend pipe
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][CEL] Loading configuration
2023/11/27 22:45:55 KRAKEND DEBUG: [CEL] Parsing expression: 'app2.example.com' in req_headers['Host']
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][CEL] 1 preEvaluator(s) loaded
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][CEL] 0 postEvaluator(s) loaded
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /] Building the http handler
2023/11/27 22:45:55 KRAKEND DEBUG: [ENDPOINT: /][JWTSigner] Signer disabled
2023/11/27 22:45:55 KRAKEND INFO: [ENDPOINT: /][JWTValidator] Validator disabled for this endpoint
panic: handlers are already registered for path '/'

goroutine 1 [running]:
github.com/gin-gonic/gin.(*node).addRoute(0x2dc22d6?, {0xc000a9c92b, 0x1}, {0xc000597100?, 0x4, 0x4})
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:260 +0x734
github.com/gin-gonic/gin.(*Engine).addRoute(0xc000583040, {0x2dc22d6, 0x3}, {0xc000a9c92b, 0x1}, {0xc000597100, 0x4, 0x4})
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:335 +0x272
github.com/gin-gonic/gin.(*RouterGroup).handle(0xc0005a2c80, {0x2dc22d6, 0x3}, {0x355f598?, 0x0?}, {0xc000922e28, 0x1, 0xc000bbec98?})
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/routergroup.go:89 +0x145
github.com/gin-gonic/gin.(*RouterGroup).GET(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/routergroup.go:117
github.com/luraproject/lura/v2/router/gin.ginRouter.registerKrakendEndpoint({{0xc000583040, {0x0, 0x0, 0x0}, 0xc00052a6a0, {0x357ee80, 0xc000ac6840}, {0x35981c8, 0xc00052a220}, 0xc00052a6e0}, ...}, ...)
        /go/pkg/mod/github.com/luraproject/lura/v2@v2.3.0/router/gin/router.go:163 +0x209
github.com/luraproject/lura/v2/router/gin.ginRouter.registerKrakendEndpoints({{0xc000583040, {0x0, 0x0, 0x0}, 0xc00052a6a0, {0x357ee80, 0xc000ac6840}, {0x35981c8, 0xc00052a220}, 0xc00052a6e0}, ...}, ...)
        /go/pkg/mod/github.com/luraproject/lura/v2@v2.3.0/router/gin/router.go:147 +0x1cd
github.com/luraproject/lura/v2/router/gin.ginRouter.registerEndpointsAndMiddlewares({{0xc000583040, {0x0, 0x0, 0x0}, 0xc00052a6a0, {0x357ee80, 0xc000ac6840}, {0x35981c8, 0xc00052a220}, 0xc00052a6e0}, ...}, ...)
        /go/pkg/mod/github.com/luraproject/lura/v2@v2.3.0/router/gin/router.go:129 +0x2b8
github.com/luraproject/lura/v2/router/gin.ginRouter.Run({{0xc000583040, {0x0, 0x0, 0x0}, 0xc00052a6a0, {0x357ee80, 0xc000ac6840}, {0x35981c8, 0xc00052a220}, 0xc00052a6e0}, ...}, ...)
        /go/pkg/mod/github.com/luraproject/lura/v2@v2.3.0/router/gin/router.go:103 +0x138
github.com/krakendio/krakend-ce/v2.(*ExecutorBuilder).NewCmdExecutor.func1({{0x0, 0x0}, {0xc000808630, 0x2, 0x2}, {0x0, 0x0, 0x0}, 0x2540be400, 0x0, ...})
        /github/workspace/executor.go:205 +0xe62
github.com/krakendio/krakend-cobra/v2.runFunc(0x46bdf60?, {0x2dc4bd8?, 0x3?, 0x3?})
        /go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.2.0/run.go:24 +0x255
github.com/spf13/cobra.(*Command).execute(0x46bdf60, {0xc000ac7410, 0x3, 0x3})
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x46bda60)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/krakendio/krakend-cobra/v2.Root.Execute({{0x46bda60, {0x0, 0x0, 0x0}, 0xc000a96920}, {0xc000aba1a0, 0x5, 0x5}, 0xc000a96980}, {0x3579320, ...}, ...)
        /go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.2.0/cmd.go:129 +0xaf
github.com/krakendio/krakend-cobra/v2.ExecuteRoot({0x3579320, 0xc00059c000}, 0x2e5bae9?, {{0x46bda60, {0x0, 0x0, 0x0}, 0xc000a96920}, {0xc000aba1a0, 0x5, ...}, ...})
        /go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.2.0/cmd.go:26 +0xa5
github.com/krakendio/krakend-cobra/v2.Execute(...)
        /go/pkg/mod/github.com/krakendio/krakend-cobra/v2@v2.2.0/cmd.go:21
main.main()
        /github/workspace/cmd/krakend-ce/main.go:60 +0x64a
```

**Additional comments:**

**Comment by alombarte** [comment]
Hi @fabubacker ,

This is supported out of the box in the Enterprise edition: https://www.krakend.io/docs/enterprise/service-settings/virtual-hosts/ but not in the community. 

You can make conditional requests with CEL in CE, but you should have multiple backends, not endpoints. You cannot create an endpoint twice.

You can also use Lua scripts and Go pugins to support this scenario, there are plenty of options

**Comment by fabubacker** [comment]
Thanks @alombarte for the response. With CEL and multiple backends, how to differentiate the request between backends with two different domain names? Is it possible in community edition without any customization like Lua scripts and Go pugins? The apps we are looking to onboard in api gateway are simple ones so not looking to making it as complex with custom scripts.

**Comment by fabubacker** [comment]
Thanks @alombarte it is working but not fitting my scenario as I am using Krakend as proxy for the backends. Looks like `no-op` cannot be used for endpoints with more than one backend.
